"use strict";
const E=id=>document.getElementById(id),S=document.createElement("style");S.textContent='.room{position:relative;height:240px;margin:15px;border:2px solid #7784bb;border-radius:24px;background:#18204a;overflow:hidden}.cat{position:absolute;left:48%;bottom:30px;font-size:70px}.decor{position:absolute;font-size:30px}.currency{color:#fff19b;font-weight:900}.row{display:flex;gap:9px;justify-content:center;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:15px}.item{padding:12px;border:1px solid #6575a8;border-radius:13px;background:#111733}.pbtn{position:fixed;right:18px;bottom:18px;z-index:8}.screen{z-index:10}@media(max-width:600px){.grid{grid-template-columns:1fr}}';document.head.append(S);
E("start").innerHTML='<div class="panel"><h1>Cosmic Cat Lobby</h1><div class="currency">⭐ STAR TOKENS <span id="tokens">0</span></div><div id="room" class="room"><div id="decor"></div><div id="lobbyCat" class="cat">🐱</div></div><p>Fashion discoveries decorate your spaceship forever.</p><div class="row"><button id="go2">🚀 START MISSION</button><button id="shopBtn">⭐ COSMIC SHOP</button></div></div>';
document.body.insertAdjacentHTML("beforeend",'<button id="pauseBtn" class="pbtn hidden">Ⅱ MENU</button><div id="pauseMenu" class="screen hidden"><div class="panel"><h1>PAUSED</h1><div class="row"><button id="resumeBtn">RESUME</button><button id="restartBtn">RESTART</button><button id="lobbyBtn">LOBBY</button></div></div></div><div id="shop" class="screen hidden"><div class="panel"><h1>COSMIC SHOP</h1><div class="currency">⭐ <span id="shopTokens">0</span></div><div class="row"><button data-tab="skin">SKINS</button><button data-tab="theme">THEMES</button><button data-tab="effect">EFFECTS</button></div><div id="shopGrid" class="grid"></div><button id="shopBack">BACK</button></div></div>');
let meta={tokens:0,maxFashion:0,owned:["blue","space","star"],skin:"blue",theme:"space",effect:"star"};try{Object.assign(meta,JSON.parse(localStorage.cosmicCatMeta2||"{}"))}catch(e){}const save=()=>localStorage.cosmicCatMeta2=JSON.stringify(meta);
const I=[["blue","skin","Starlight Blue",0,"🐱"],["gold","skin","Solar Gold",12,"😺"],["void","skin","Void Royal",22,"🐈‍⬛"],["space","theme","Deep Space",0,"🌌"],["pink","theme","Pink Nebula",18,"💜"],["aurora","theme","Aurora Deck",28,"🌈"],["star","effect","Starlight Trail",0,"✨"],["heart","effect","Heart Blaster",15,"💖"],["prism","effect","Prism Power",30,"💫"]].map(x=>({id:x[0],type:x[1],name:x[2],cost:x[3],icon:x[4]}));
function lobby(){E("tokens").textContent=meta.tokens;E("shopTokens").textContent=meta.tokens;let d=["🪴","🏆","🛋️","🔭","🪐","🎵","💎","👑","🪽","🌟"];E("decor").innerHTML=d.slice(0,Math.ceil(meta.maxFashion/2)).map((x,i)=>'<span class="decor" style="left:'+(4+(i*18)%88)+'%;top:'+(20+(i*41)%155)+'px">'+x+'</span>').join("");E("lobbyCat").textContent=(I.find(x=>x.id===meta.skin)||I[0]).icon;E("room").style.background=meta.theme==="pink"?"#512752":meta.theme==="aurora"?"#0d514d":"#18204a"}
function shop(t="skin"){E("shopTokens").textContent=meta.tokens;E("shopGrid").innerHTML=I.filter(x=>x.type===t).map(x=>{let o=meta.owned.includes(x.id),q=meta[t]===x.id;return '<div class="item"><div style="font-size:34px">'+x.icon+'</div><b>'+x.name+'</b><p>'+(o?(q?"EQUIPPED":"OWNED"):"⭐ "+x.cost)+'</p><button data-buy="'+x.id+'">'+(q?"✓":o?"EQUIP":"BUY")+'</button></div>'}).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{let x=I.find(i=>i.id===b.dataset.buy);if(!meta.owned.includes(x.id)){if(meta.tokens<x.cost)return alert("Not enough Star Tokens!");meta.tokens-=x.cost;meta.owned.push(x.id)}meta[x.type]=x.id;save();shop(t);lobby()})}
function toggle(){if(!running)return;paused=!paused;E("pauseMenu").classList.toggle("hidden",!paused);if(!paused)last=performance.now()}function home(){running=false;paused=false;["pauseMenu","over","shop"].forEach(x=>E(x).classList.add("hidden"));E("pauseBtn").classList.add("hidden");E("start").classList.remove("hidden");lobby();draw()}
E("go2").onclick=()=>{begin();E("pauseBtn").classList.remove("hidden")};E("shopBtn").onclick=()=>{E("shop").classList.remove("hidden");shop()};E("shopBack").onclick=()=>E("shop").classList.add("hidden");document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>shop(b.dataset.tab));E("pauseBtn").onclick=toggle;E("resumeBtn").onclick=toggle;E("restartBtn").onclick=()=>{E("pauseMenu").classList.add("hidden");begin()};E("lobbyBtn").onclick=home;addEventListener("keydown",e=>{if(e.code==="Escape")toggle()});
let F=showFashionUnlock;showFashionUnlock=n=>{F(n);if(n>meta.maxFashion){meta.maxFashion=n;meta.tokens+=2;save()}};let D=defeatEnemy;defeatEnemy=(e,a=true)=>{if(!e.dead&&Math.random()<.018){meta.tokens++;save()}D(e,a)};let Z=endGame;endGame=()=>{let r=Math.max(1,Math.floor(level/6)+Math.floor(elapsed/120));meta.tokens+=r;meta.maxFashion=Math.max(meta.maxFashion,Math.min(20,Math.floor(level/5)));save();Z();E("pauseBtn").classList.add("hidden");E("result").innerHTML+="<br><b>⭐ +"+r+" permanent Star Tokens</b>"};
addEnemy=()=>{let a=Math.random()*6.283,d=Math.max(width,height)*.7,t=elapsed,p=t>150?5:t>100?4:t>65?3:t>35?2:t>15?1:0,k=Math.floor(Math.random()*(p+1));enemies.push({x:player.x+Math.cos(a)*d,y:player.y+Math.sin(a)*d,r:[11,16,24,13,29,38][k],hp:[22,48,115,72,190,420][k]*(1+t/150),speed:[66,48,32,105,38,27][k]+t*.12,damage:[10,16,23,13,27,36][k],color:["#ff578a","#ffa148","#9867ff","#55efc4","#ff4fd8","#e9e36a"][k],value:[1,2,5,3,8,16][k],kind:Math.min(k,2)})};lobby();
S.textContent+=' .token-hud{position:fixed;z-index:7;right:20px;top:88px;padding:8px 13px;border:1px solid #fff09a;border-radius:999px;background:#241b43dd;color:#fff19b;font-weight:900;pointer-events:none}.token-pop{position:fixed;z-index:30;left:50%;top:19%;transform:translate(-50%,-50%);padding:12px 19px;border:2px solid #fff2a3;border-radius:18px;background:#332157ee;color:#fff4a9;font-size:22px;font-weight:900;pointer-events:none;opacity:0}.token-pop.show{animation:tokenPop 1.5s ease both}@keyframes tokenPop{0%{opacity:0;transform:translate(-50%,-20%) scale(.7)}18%,70%{opacity:1;transform:translate(-50%,-50%) scale(1.08)}100%{opacity:0;transform:translate(-50%,-90%) scale(.95)}}';
document.body.insertAdjacentHTML("beforeend",'<div id="tokenHud" class="token-hud hidden">⭐ <span id="runTokens">0</span></div><div id="tokenPop" class="token-pop"></div>');
let tokenPopTimer=0;
function tokenFeedback(n,label){if(n<=0)return;E("runTokens").textContent=meta.tokens;let p=E("tokenPop");p.textContent="⭐ +"+n+" STAR TOKEN"+(n===1?"":"S")+" · "+label;clearTimeout(tokenPopTimer);p.classList.remove("show");void p.offsetWidth;p.classList.add("show");tokenPopTimer=setTimeout(()=>p.classList.remove("show"),1500)}
let tf=showFashionUnlock;showFashionUnlock=n=>{let b=meta.tokens;tf(n);tokenFeedback(meta.tokens-b,"FASHION BONUS")};
let td=defeatEnemy;defeatEnemy=(e,a=true)=>{let b=meta.tokens;td(e,a);tokenFeedback(meta.tokens-b,"LUCKY DROP")};
let te=endGame;endGame=()=>{let b=meta.tokens;te();tokenFeedback(meta.tokens-b,"MISSION REWARD");E("tokenHud").classList.add("hidden")};
let tb=begin;begin=()=>{tb();E("runTokens").textContent=meta.tokens;E("tokenHud").classList.remove("hidden")};E("go2").onclick=()=>{begin();E("pauseBtn").classList.remove("hidden")};
let th=home;home=()=>{th();E("tokenHud").classList.add("hidden")};E("lobbyBtn").onclick=home;
I.push(
{id:"tiger",type:"skin",name:"Nebula Tiger",cost:16,icon:"🐯"},{id:"lion",type:"skin",name:"Solar Lion",cost:26,icon:"🦁"},{id:"robot",type:"skin",name:"Mecha Cat",cost:38,icon:"🤖"},{id:"alien",type:"skin",name:"Alien Kitty",cost:48,icon:"👽"},
{id:"sunset",type:"theme",name:"Supernova Lounge",cost:14,icon:"🌅"},{id:"moon",type:"theme",name:"Moon Palace",cost:24,icon:"🌙"},{id:"garden",type:"theme",name:"Cosmic Garden",cost:34,icon:"🌌"},{id:"royal",type:"theme",name:"Royal Starship",cost:46,icon:"🏰"},
{id:"paw",type:"effect",name:"Paw Comets",cost:12,icon:"🐾"},{id:"rainbow",type:"effect",name:"Rainbow Drive",cost:22,icon:"🌈"},{id:"lightning",type:"effect",name:"Thunder Shots",cost:32,icon:"⚡"},{id:"galaxy",type:"effect",name:"Galaxy Bloom",cost:45,icon:"💫"});
let tl=lobby;lobby=()=>{tl();let c={sunset:"linear-gradient(145deg,#732d55,#f08b61)",moon:"linear-gradient(145deg,#10183e,#6874bd)",garden:"linear-gradient(145deg,#123c39,#315f72)",royal:"linear-gradient(145deg,#3f205c,#b98233)"};if(c[meta.theme])E("room").style.background=c[meta.theme]};
upgrades.push(
{id:"paws",name:"Comet Paws",text:"Move 14% faster.",apply:()=>player.move*=1.14},
{id:"nineLives",name:"Nine Lives",text:"Gain 18 maximum HP and heal 18 HP.",apply:()=>{player.maxHp+=18;player.hp=Math.min(player.maxHp,player.hp+18)}},
{id:"gravity",name:"Gravity Whiskers",text:"Pull shards in from 55px farther away.",apply:()=>player.magnet+=55},
{id:"piercing",name:"Piercing Claws",text:"Projectiles pass through 1 more enemy.",apply:()=>player.pierce++},
{id:"lightSpeed",name:"Light-Speed Yarn",text:"Shots fly 22% faster and grow larger.",apply:()=>{player.bulletSpeed*=1.22;player.bulletSize+=.3}},
{id:"warp",name:"Warp Tail",text:"Dash recharges 18% faster.",apply:()=>player.dashMax=Math.max(.38,player.dashMax*.82)},
{id:"reactor",name:"Purr Reactor",text:"Gain 22% damage and 8% attack speed.",apply:()=>{player.damage*=1.22;player.rate/=1.08}},
{id:"medic",name:"Royal Catnap",text:"Regenerate 22% faster and heal 8 HP.",apply:()=>{player.regenInterval*=.78;player.hp=Math.min(player.maxHp,player.hp+8)}});
let sr=reset;reset=()=>{sr();["paws","nineLives","gravity","piercing","lightSpeed","warp","reactor","medic"].forEach(id=>player.upgradeLevels[id]=0)};
